package lox;

enum TokenType {
    SEMICOLON, COMMA, DOT, L_PAREN, R_PAREN, L_BRACE, R_BRACE,

    PLUS, MINUS, STAR, SLASH, MOD, HAT, PLUS_PLUS, MINUS_MINUS, PLUS_EQ, MINUS_EQ,

    EQ, EQ_EQ, GREATER, GREATER_EQ, LESS, LESS_EQ, BANG, BANG_EQ,

    NUMBER, STRING, IDENTIFIER,

    VAR, TRUE, FALSE, NIL, AND, OR, IF, ELSE, THEN, RETURN, BREAK, FN, FOR, WHILE, CLASS, THIS, SUPER, PRINT,

    EOF
}
