enum TokenType {
    SEMICOLON, COMMA, DOT, LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,

    PLUS, MINUS, STAR, SLASH, MOD, EXP, PLUS_PLUS, MINUS_MINUS,

    EQUAL, EQUAL_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL, BANG, BANG_EQUAL,

    IDENTIFIER, STRING, NUMBER,

    VAR, THIS, TRUE, FALSE, SUPER, CLASS, AND, OR, IF, ELSE, ELIF, RETURN,

    EOF
}
